#
# This file is part of Saft.
#
# (c) Konrad Abicht <hi@inspirito.de>
# (c) Natanael Arndt <arndt@informatik.uni-leipzig.de>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#

#
# This file contains a list with different configurations for test cases which rely on store.
#
# Feel free to copy it to test-config.yml and adapt. You can reuse existing configurations or you can use your own.

httpConfig: &httpConfig
    authUrl: "http://virtuoso:8890/sparql-auth"
    queryUrl: "http://virtuoso:8890/sparql"
    username: "dba"
    password: "dba"
